# Generated by Django 5.2.15 on 2026-07-30 12:10

import orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_cancellation_reason_order_delivered_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invoice',
            field=models.FileField(blank=True, help_text='Generated PDF invoice', null=True, upload_to=orders.models.invoice_upload_path),
        ),
    ]
