# Generated by Django 5.2.15 on 2026-07-31 11:24

import django.core.files.storage
import orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='invoice',
            field=models.FileField(blank=True, help_text='Generated PDF invoice', null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/invoices/', location='C:\\Users\\LENOVO\\OneDrive\\Desktop\\KurtiShop\\Kurtishop\\media\\invoices'), upload_to=orders.models.invoice_upload_path),
        ),
    ]
