# Generated by Django 5.2.15 on 2026-08-12 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_returnrequest_returnrequestitem'),
        ('products', '0011_alter_occasion_image_alter_productimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequestitem',
            name='exchanged_to_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='products.productvariant'),
        ),
        migrations.AddField(
            model_name='returnrequestitem',
            name='fulfilled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='returnrequestitem',
            name='new_color',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='returnrequestitem',
            name='new_product_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='returnrequestitem',
            name='new_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='returnrequestitem',
            name='new_size',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='returnrequestitem',
            name='new_unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='returnrequestitem',
            name='new_variant_sku',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='returnrequestitem',
            name='price_difference',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('fulfilled', 'Exchange Fulfilled')], default='pending', max_length=20),
        ),
    ]
