# Generated by Django 5.2.15 on 2026-08-14 08:51

import orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_returnrequestitem_exchanged_to_variant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='invoice',
            field=models.FileField(blank=True, help_text='Generated PDF invoice', null=True, upload_to=orders.models.invoice_upload_path),
        ),
    ]
