# Generated by Django 5.2.15 on 2026-08-14 09:26

import cloudinary_storage.storage
import orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='invoice',
            field=models.FileField(blank=True, help_text='Generated PDF invoice', null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to=orders.models.invoice_upload_path),
        ),
    ]
