# Generated by Django 5.2.15 on 2026-07-08 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='session_key',
            field=models.CharField(db_index=True, max_length=40, unique=True),
        ),
    ]
