# Generated by Django 5.2.15 on 2026-06-29 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_add_models'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Occassion',
            new_name='Occasion',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='occassion',
            new_name='occasion',
        ),
    ]
