# Generated by Django 5.2.15 on 2026-06-30 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_productimage_options_productimage_alt_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='view',
            field=models.CharField(choices=[('front', 'Front'), ('back', 'Back'), ('left', 'Left Side'), ('right', 'Right Side'), ('three-quarter', '3/4 View'), ('closeup', 'Close Up'), ('detail', 'Detail')], default='front', max_length=50),
        ),
    ]
