# Generated by Django 5.2.15 on 2026-07-27 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_productattribute_alter_productimage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='occasion',
            name='image',
            field=models.ImageField(blank=True, help_text='Recommended size: 400×400 px', null=True, upload_to='occasions/'),
        ),
    ]
