# Generated by Django 5.2.15 on 2026-07-27 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_occasion_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='occasion',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Show this occasion on the homepage (Shop By Occasion)'),
        ),
    ]
