# Generated by Django 5.2.15 on 2026-07-28 20:01

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_occasion_is_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occasion',
            name='image',
            field=models.ImageField(blank=True, help_text='Recommended size: 400×400 px', max_length=500, null=True, upload_to='occasions/'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(max_length=500, upload_to=products.models.product_image_upload_path),
        ),
    ]
