# Generated by Django 5.2.15 on 2026-08-13 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_occasion_image_alter_productimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceablePincode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.CharField(max_length=6, unique=True)),
                ('area_name', models.CharField(help_text='e.g. Taliparamba, Kannur City', max_length=100)),
                ('district', models.CharField(default='Kannur', max_length=100)),
                ('state', models.CharField(default='Kerala', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Serviceable Pincode',
                'verbose_name_plural': 'Serviceable Pincodes',
                'ordering': ['pincode'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='allowed_pincodes',
            field=models.ManyToManyField(blank=True, help_text='Leave empty = available in ALL serviceable pincodes. Select specific pincodes to restrict delivery of this product.', related_name='products', to='products.serviceablepincode'),
        ),
    ]
